### ISSUE TITLE
Possible bug when using `getfielddim` and the `MixedDofHandler`

### ISSUE THREAD

**Issue by DRollin** [Ferrite-FEM/FerriteViz.jl#76]
Hello,
I recently updated Ferrite to v0.3.14 and now a part of my old code fails with the following message:
"MethodError: no method matching getfielddim(::MixedDofHandler{3, Float64, Ferrite.Grid{3, Tetrahedron, Float64}}, ::Int64)"
If I am correct the problem is the following line:
https://github.com/Ferrite-FEM/FerriteViz.jl/blob/023eb0dbd528945c41e9baeb388b88b26d79281b/src/utils.jl#L329
Where `field_idx::Int` works for a `DofHandler`, but not for a `MixedDofHandler`.
Am I correct, or am I missing something?

**Comment by KnutAM** [comment]
I think you need to use `field_idx = (1, your_field_idx)`
Alternatively use the output of `find_field(dh, fieldname)` which should be an NTuple{2,Int} for `MixedDofHandler`
https://github.com/Ferrite-FEM/Ferrite.jl/blob/856dc2816baa9cc7fabcfb0ad58cc8aa8d2c0ee4/src/Dofs/DofHandler.jl#L171

**Comment by koehlerson** [comment]
There's a PR for MixedDofHandler support. You need to use this branch

**Comment by koehlerson** [comment]
https://github.com/Ferrite-FEM/FerriteViz.jl/pull/70

**Comment by DRollin** [comment]
Thanks for the hint!
And thank you for your great work, this package is super helpful :star_struck:
