### ISSUE TITLE
ERROR: MethodError: no method matching ntriangles(::QuadraticTriangle)

### ISSUE THREAD

**Issue by khorrami1** [Ferrite-FEM/FerriteViz.jl#84]
When I run the following code:
`using Ferrite, FerriteViz;
import GLMakie;
grid = generate_grid(QuadraticTriangle, (3, 3));
wireframe(grid);`
, I get this Error: ERROR: MethodError: no method matching ntriangles(::QuadraticTriangle)

**Comment by termi-official** [comment]
The fix is already in https://github.com/Ferrite-FEM/FerriteViz.jl/pull/83 . We will try to merge it soon and make a new release.
