### ISSUE TITLE
Put some examples into the readme

### ISSUE THREAD

**Issue by termi-official** [Ferrite-FEM/FerriteViz.jl#87]
Title checks out. What do we want to include? Proposal

1. ![logo](https://github.com/Ferrite-FEM/FerriteViz.jl/assets/9196588/3eac3679-92b2-4167-8372-6a6476495404)

and I can put in a heart chamber simulation. What else?

**Comment by koehlerson** [comment]
I think the Ferrite Logo is very nice, but I'd prefer if we ask @kimauth how to mimic the style of her gif here: https://github.com/kimauth/FerriteCon2022.jl/blob/main/plotting/logo_animation.gif

with https://github.com/kimauth/FerriteCon2022.jl/blob/main/plotting/logo_animation.jl#L61-L66C46

**Comment by kimauth** [comment]
I would really insist on using the correct aspect ratio, but other than that it is probably just putting a scaling factor on the displacements that makes the difference (+playback speed). The unconventionally numbered cohesive elements are not straight forward to visualize with FerriteViz, right?

**Comment by termi-official** [comment]
I need to ask what the visualization of the cohesive zone elements should look like, because from my understanding these are just an implementation trick to track which faces stick together and hence they geometry is "empty". If you just want to render the solution over these cells it should be straight forward., because you just have to redispatch the `decompose!` (i.e. copy paste https://github.com/Ferrite-FEM/FerriteViz.jl/blob/master/src/utils.jl#L226-L270 and swap indices) and the `ntriangles` (something like `ntriangles(::CohesiveZoneQuad) = 4` functions.

**Comment by termi-official** [comment]
However I would like to leave this example for the docs and not merge it into master to have a concrete example in the docs showing how to integrate custom element formulations into the framework.

**Comment by kimauth** [comment]
One could for example visualize the cohesive tractions, much like visualizing stresses. There can totally be good reasons to not visualize them though and I think the logo animation is nice with or without showing the cohesive elements :)

**Comment by termi-official** [comment]
https://github.com/termi-official/FerriteVizLogo.jl here is the update

**Comment by termi-official** [comment]
@koehlerson can you add the rotating cantilever gif from MakieCon?
